#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

export WM_COMPILER=Mpicc

cd adapter
wclean && wmake lib

cd ../solvers

# wmake -all solvers
cd buoyantBoussinesqPimpleFoam; wclean && wmake; cd ..
cd laplacianFoam; wclean && wmake; cd ..
cd buoyantPimpleFoam; wclean && wmake; cd ..
cd buoyantSimpleFoam; wclean && wmake; cd ..
